#!/usr/bin/env python3

import logging
import argparse
import yaml

import se.scripts.logging

from se.jobs import Job
from se.tasks import Configuration, Echo, Copy, Command, Template, Getenv
from se.scripts import SimpleScriptEngine

DRY_RUN = False
DEBUG = False
QUIET = False

def parse_command_line_arguments():

    global QUIET
    global DEBUG
    global DRY_RUN

    arg_parser = argparse.ArgumentParser(description='ScriptEngine command line tool')

    arg_parser.add_argument('--dry-run', help='Don\'t actually run any commands', action='store_true')
    arg_parser.add_argument('-q', '--quiet', help='Be quiet', action='store_true')
    arg_parser.add_argument('--debug', help='Debug output', action='store_true')
    arg_parser.add_argument('file', help='YAML files to read', nargs='+')

    args = arg_parser.parse_args()

    QUIET = args.quiet
    DEBUG = args.debug
    DRY_RUN = args.dry_run

    return args.file

def create_job_from_dict(dictionary):

    log = logging.getLogger('se.jobs')

    TASK_CLASSES = { 'echo': Echo,
                     'copy': Copy,
                     'command': Command,
                     'template': Template,
                     'config': Configuration,
                     'getenv': Getenv }
    SIMPLE_JOB = set(TASK_CLASSES.keys())
    COMPOSITE_JOB = { 'do' }
    JOB_MODIFIERS = { 'when', 'loop', 'context' }

    job_name = set(dictionary.keys()) & (COMPOSITE_JOB | SIMPLE_JOB)
    if len(job_name) != 1:
        raise RuntimeError('Missing, unknown or ambiguous job/task name')
    else:
        job_name = job_name.pop()

    job_modifiers = set(dictionary.keys()) & JOB_MODIFIERS

    if {job_name} | job_modifiers != set(dictionary.keys()):
        raise RuntimeError('Unknown keywords in job description')

    log.debug('Creating "{}" job'.format(job_name))
    job = Job()

    if job_name in COMPOSITE_JOB:
        log.debug('It is a composite job')
        sub_job = Job(tasks=None,
                      when=dictionary.get('when', None),
                      loop=dictionary.get('loop', None),
                      context=dictionary.get('context', None))
        for j in dictionary[job_name]:
            sub_job.append(create_job_from_dict(j))
        job.append(sub_job)

    elif job_name in SIMPLE_JOB:

        log.debug('Creating task')
        task = TASK_CLASSES[job_name](dictionary[job_name])
        if job_modifiers:
            log.debug('Adding this task with job modifiers {}'.format(job_modifiers))
            job.append(Job(tasks=task,
                           when=dictionary.get('when', None),
                           loop=dictionary.get('loop', None),
                           context=dictionary.get('context', None)))
        else:
            log.debug('Adding as simple task')
            job.append(task)
    return job


if __name__ == '__main__':

    files = parse_command_line_arguments()

    if QUIET:
        log = se.scripts.logging.app_logger('se', level=logging.WARN)
    elif DEBUG:
        log = se.scripts.logging.app_logger('se', level=logging.DEBUG)
    else:
        log = se.scripts.logging.app_logger('se', level=logging.INFO)

    if DRY_RUN:
        log.info('Running in dry-run mode')

    script = []
    for file in files:
        log.info('Processing file {}'.format(file))
        with open(file) as f:
            scr = yaml.safe_load(f)
        script.extend(scr)

    job = Job()
    for j in script:
        job.append(create_job_from_dict(j))

    SimpleScriptEngine().run(script=[job], dryrun=DRY_RUN)
